In [23]:
import torch
from torch.autograd import Variable

# 定义三个Variable变量
x = Variable(torch.Tensor([1,2,3]),requires_grad=True)
w = Variable(torch.Tensor([2,3,4]),requires_grad=True)
b = Variable(torch.Tensor([3,4,5]),requires_grad=True)
print(x)
print(w)
print(b)

tensor([1., 2., 3.], requires_grad=True)
tensor([2., 3., 4.], requires_grad=True)
tensor([3., 4., 5.], requires_grad=True)


In [28]:
# 构建函数
y = w * x * x + b
y

tensor([ 5., 16., 41.], grad_fn=<AddBackward0>)

In [29]:
# 自动求导，计算梯度
y.backward(torch.Tensor([1,1,1]))
print(x.grad)
print(w.grad)
print(b.grad)

tensor([ 8., 24., 48.])
tensor([ 2.,  8., 18.])
tensor([4., 4., 4.])


In [ ]:
# 上述代码的计算图为y = w * x^2 + b。
# 对x, w, b分别求偏导为
# x.grad = 2wx，w.grad=x^2，b.grad=1。
# 代值检验可得计算结果是正确的。