In [7]:
import torch
torch.__version__

'1.1.0'

In [9]:
x = torch.Tensor([[1,2],[3,4],[5,6]])
x

tensor([[1., 2.],
        [3., 4.],
        [5., 6.]])

In [6]:
x1 = torch.ones((2,6))
x1

tensor([[1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.]])

In [10]:
x2 = torch.rand(2,6)
x2

tensor([[0.0546, 0.6084, 0.4663, 0.9997, 0.4153, 0.1438],
        [0.6430, 0.8651, 0.1887, 0.2455, 0.5603, 0.0521]])

In [15]:
import numpy as np
x2_numpy = x2.numpy()
x2.numpy()

array([[0.05460429, 0.6083741 , 0.46630216, 0.9997185 , 0.41530603,
        0.14380145],
       [0.642993  , 0.86507934, 0.18873125, 0.24550325, 0.5602786 ,
        0.05205601]], dtype=float32)

In [16]:
x3 = np.array([[1,2],[3,4],[5,6]])
x3

array([[1, 2],
       [3, 4],
       [5, 6]])

In [18]:
x3_torch = torch.from_numpy(x3)
x3_torch

tensor([[1, 2],
        [3, 4],
        [5, 6]], dtype=torch.int32)